version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '10:00'
    open-pull-requests-limit: 10
    reviewers:
      - dustinsgoodman
    labels:
      - dependency
    ignore:
      # @nrwl deps should always be updated by running `npx nx migrate @nrwl/workspace`
      - dependency-name: '@nrwl/*'
      - dependency-name: 'nx'
