service: public-api
plugins:
  - serverless-s3-remover
  - serverless-esbuild
  - serverless-analyze-bundle-plugin
  - serverless-offline
frameworkVersion: '3'
useDotenv: true

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true
  patterns:
    - 'handler.js'
    - '!node_modules/**'
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  httpApi:
    cors: true
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: '*'

functions:
  graphql:
    handler: src/handlers/graphql.server
    events:
      - httpApi:
          path: /graphql
          method: post
      - httpApi:
          path: /graphql
          method: get

  healthcheck:
    handler: src/handlers/healthcheck.handler
    events:
      - httpApi:
          path: /healthcheck
          method: get
