name: CI

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Create AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key: xxx
          secret: xxx

      - name: Create .env file
        run: |
          touch .env
          echo IS_OFFLINE=$IS_OFFLINE >> .env
          echo SLS_STAGE=$SLS_STAGE >> .env
        env:
          IS_OFFLINE: ${{ secrets.IS_OFFLINE }}
          SLS_STAGE: ${{ secrets.SLS_STAGE }}

      - name: Generate service
        run: yarn workspace-generator service test-service

      - name: Generate library
        run: yarn workspace-generator lib test-lib

      - name: Linting
        run: yarn lint:all

      - name: Run tests
        run: yarn test:all

      - name: Run sls package
        run: yarn build:all
