name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Create AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key: ${{ secrets.AWS_ACCESS_KEY }}
          secret: ${{ secrets.AWS_SECRET }}

      - name: Create .env file for testing
        run: |
          touch .env.test
          echo IS_OFFLINE${{ secrets.IS_OFFLINE }} >> .env
          echo SLS_STAGE=${{ secrets.SLS_STAGE }} >> .env
          cat .env.test

      - name: Generate service
        run: yarn workspace-generator service test-service

      - name: Generate library
        run: yarn workspace-generator lib test-lib

      - name: Linting
        run: yarn lint:all

      - name: Run tests
        run: yarn test:all

      - name: Create .env file for deployment
        run: |
          touch .env
          echo IS_OFFLINE${{ secrets.IS_OFFLINE }} >> .env
          echo SLS_STAGE=${{ secrets.SLS_STAGE }} >> .env
          cat .env

      - name: Run sls package
        run: yarn build:all

      # - name: Deploy SLS Preview
      #   if: github.ref != 'refs/heads/main'
      #   run: npx nx run deploy:all --stage=${GITHUB_HEAD_REF}
      # - name: Deploy SLS Dev
      #   if: github.ref == 'refs/heads/main'
      #   run: npx nx run deploy:all --stage=dev
