name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Create AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key: xxx
          secret: xxx
      - name: Create .env file
        run: |
          touch .env
          echo IS_OFFLINE=$IS_OFFLINE >> .env
          echo SLS_STAGE=$SLS_STAGE >> .env
        env:
          IS_OFFLINE: ${{ secrets.IS_OFFLINE }}
          SLS_STAGE: ${{ secrets.SLS_STAGE }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install packages
        run: yarn install --frozen-lockfile

  service-generator:
    runs-on: ubuntu-latest
    needs: ['setup']
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Generate service
        run: yarn workspace-generator service test-service

  lib-generator:
    runs-on: ubuntu-latest
    needs: ['setup']
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Generate library
        run: yarn workspace-generator lib test-lib

  lint:
    runs-on: ubuntu-latest
    needs: ['setup']
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Linting
        run: yarn lint:all

  test:
    runs-on: ubuntu-latest
    needs: ['setup']
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Run tests
        run: yarn test:all

  build:
    runs-on: ubuntu-latest
    needs: ['service-generator', 'lib-generator', 'lint', 'test']
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Run sls package
        run: yarn build:all
