# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key: xxx
          secret: xxx

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Generate service
        run: yarn workspace-generator service test-service

      - name: Generate library
        run: yarn workspace-generator lib test-lib

      - name: Linting
        run: yarn lint:all

      - name: Create .env file
        run: |
          touch .env
          echo IS_OFFLINE=$IS_OFFLINE >> .env
          echo SLS_STAGE=$SLS_STAGE >> .env
          echo DEMO_QUEUE_URL=$DEMO_QUEUE_URL >> .env
        env:
          IS_OFFLINE: ${{ secrets.IS_OFFLINE }}
          SLS_STAGE: ${{ secrets.SLS_STAGE }}
          DEMO_QUEUE_URL: ${{ secrets.DEMO_QUEUE_URL }}

      - name: Run tests
        run: yarn test:all

      - name: Run sls package
        run: yarn build:all
